name: Elixir CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.11'
          otp-version: '23.1'

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Dependencies and Compile
        run: MIX_ENV=test mix do deps.get, deps.compile, compile

      - name: Run Tests
        run: mix test
